#!/usr/bin/python
# coding=UTF-8
# These glyphs, and the mapping of file extensions to glyphs
# has been copied from the vimscript code that is present in
# https://github.com/ryanoasis/vim-devicons
import re;
import os;

# all those glyphs will show as weird squares if you don't have the correct patched font
# My advice is to use NerdFonts which can be found here:
# https://github.com/ryanoasis/nerd-fonts
file_node_extensions = {
 'styl': '🎨',
 'scss': '🎨',
 'htm': '🌎',
 'html': '🌎',
 'css': '🎨',
 'md': '📘',
 'markdown': '📘',
 'json': 'ℹ️',
 'js': '🌐',
 'jsx': '🌐',
 'rb': '💎',
 'php': '🌍',
 'py': '🐍',
 'pyc': '🐍',
 'pyo': '🐍',
 'pyd': '🐍',
 'coffee': '☕',
 'conf': '🐧',
 'ini': 'ℹ️',
 'yml': 'ℹ️',
 'bat': '💻',
 'jpg': '📸',
 'jpeg': '📸',
 'bmp': '🖼',
 'png': '🖼',
 'gif': '🖼',
 'ico': '🖼',
 'java': '♨',
 'db': '🗄',
 'sql': '🗄',
 'vim': '✏',
 'ai': '✏',
 'org': '📑',
 'journal': '💰',
 'psd': '🖌',
 'psb': '🖼',
 'ts': '🖼',
 'jl': '\ue624',
 'rc': '💻',
 'xml': '📰',
 'log': '📙',
 'avi': '🎥',
 'mpeg': '🎥',
 'mpg': '🎥',
 'mkv': '🎥',
 'flv': '🎥',
 'mp4': '🎥',
 'mp3': '🎵',
 'flac': '🎼',
 'wav': '🎼',
 'ogg': '🎵',
 'epub': '📚',
 'pdf': '📚',
 '7z': '📦',
 'apk': '📦',
 'bz2': '📦',
 'cab': '📦',
 'cpio': '📦',
 'deb': '📦',
 'gem': '📦',
 'gz': '📦',
 'gzip': '📦',
 'lha': '📦',
 'lzh': '📦',
 'lzma': '📦',
 'rar': '📦',
 'rpm': '📦',
 'tar': '📦',
 'tgz': '📦',
 'xz': '📦',
 'zip': '📦',
 'txt': '✍',
 'mom': '✍',
 'me': '✍',
 'ms': '✍',
 'webp': '🖼',
 'jpe': '📸',
 'svg': '🗺',
 'tif': '🖼',
 'tiff': '🖼',
 'xcf': '🖌',
 'gpg': '🔒',
 'djvu': '📚',
 'csv': '📓',
 'xlsx': '📊',
 'ods': '📊',
 'tex': '📜',
 'r': '📓',
 'R': '📓',
 'rmd': '📓',
 'Rmd': '📓',
 'm': '📊',
 'opus': '🎵',
 'm4a': '🎵',
 'webm': '🎥',
 'mov': '🎥',
 'wmv': '🎥',
 'm4b': '🎥',
 'tar.gz': '📦',
 'z64': '🎮',
 'v64': '🎮',
 'n64': '🎮',
 'gba': '🎮',
 'nes': '🎮',
 'gdi': '🎮',
 '1': 'ℹ',
 'nfo': 'ℹ',
 'info': 'ℹ',
 'iso': '📀',
 'img': '📀',
 'bib': '🎓',
 'ged': '👪',
 'part': '💔',
 'torrent': '🔽',
 'jar': '♨'}

file_node_exact_matches = {
    'exact-match-case-sensitive-1.txt' : 'X1',
    'exact-match-case-sensitive-2'     : 'X2',
    'gruntfile.coffee'                 : '',
    'gruntfile.js'                     : '',
    'gruntfile.ls'                     : '',
    'gulpfile.coffee'                  : '',
    'gulpfile.js'                      : '',
    'gulpfile.ls'                      : '',
    'dropbox'                          : '',
    '.ds_store'                        : '',
    '.gitconfig'                       : '',
    '.gitignore'                       : '',
    '.bashrc'                          : '',
    '.bashprofile'                     : '',
    'favicon.ico'                      : '',
    'license'                          : '',
    'node_modules'                     : '',
    'react.jsx'                        : '',
    'procfile'                         : '',
    '.Xdefaults'                       : '',
    '.Xresources'                      : '',
    '.dmrc'                            : '',
    '.fasd'                            : '',
    '.gitconfig'                       : '',
    '.jack-settings'                   : '',
    '.mime.types'                      : '',
    '.nvidia-settings-rc'              : '',
    '.pam_environment'                 : '',
    '.profile'                         : '',
    '.recently-used'                   : '',
    '.selected_editor'                 : '',
    '.vimrc'                           : '',
    '.xinputrc'                        : '',
    'mimeapps.list'                    : '',
    'user-dirs.dirs'                   : '',
    'ini'                              : '',
    'config'                           : ''
}

def devicon(file):
  if file.is_directory: return '📁'
  return file_node_exact_matches.get(file.relative_path, file_node_extensions.get(file.extension, '📃'))
