#! /bin/sh

localectl --no-convert set-x11-keymap us,ara pc104 ,qwerty 'grp:alt_shift_toggle,caps:swapescape' &
setxkbmap -option caps:escape &
sxhkd &
xsetroot -cursor_name left_ptr &
# --glx-no-rebind-pixmap --xrender-sync-fence
# compton -f --backend glx --glx-no-stencil -r 30 &
picom --backend glx --glx-no-stencil --blur-method kawase --blur-strength 20 --blur-background-exclude 'name ="xfce4-panel"' --blur-background-exclude 'name ="qutebrowser"' & # SHADOW -c -r 30 -C -l -30 -t -30 &
redshift &
goldendict &
nm-applet &
udiskie -t &
systemctl --user start xfce4-notifyd &
blueman-applet &
emacs --daemon &
pasystray &
syncthing-gtk -m &
parcellite &
safeeyes &
mpd &
kdeconnect-indicator &
~/.config/i3/dynamic_wallpaper.py &
notify-send.py "brightness notification" --replaces-process brightness_ctl -t 1 &
notify-send.py "volume notification" --replaces-process volume_ctl -t 1 &
if [ $HOSTNAME = "yusufs-lenovo" ]; then
    motion -b -c ~/.config/motion/motion.conf &
fi
~/.config/bspwm/start_lemonbar.py &
xfce4-panel -d & # the best sys-tray of them all
# stalonetray -bg '#000000' --grow-gravity W -i 40 --sticky --geometry 10x1+1520+0 --dockapp-mode simple --window-type dock -d none --window-strut none --window-layer bottom --kludges force_icons_size &

# polybar mybar &
# fake configs folder to use a different gtk-3.0.ini file with a different font
# env XDG_CONFIG_HOME=$HOME/.config_alt xfce4-panel -d &

bspc monitor ^1 -d I II III IV V VI VII VIII IX X
bspc monitor ^2 -d 1 2 3 4 5 6 7 8 9 10

bspc config remove_unplugged_monitors true

bspc config border_width        $((GDK_SCALE*3))
bspc config window_gap          $((GDK_SCALE*6))

bspc config split_ratio          0.7
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# colors
bspc config normal_border_color '#928374'
bspc config active_border_color '#fabd2f'
bspc config focused_border_color '#fabd2f'

for desk in {I,X,IX,VIII};do
bspc desktop $desk --layout monocle
done
#open Funny Java Things
# bspc config focus_follows_pointer false
wmname LG3D &

bspc config focus_follows_pointer true
bspc config external_rules_command "$(which external_rules)"
# bspc config pointer_follows_focus true

bspc config -m ^1 top_padding $((GDK_SCALE * 20))

bspc rule -a zathura state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a emacs state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a qutebrowser desktop='^1'
bspc rule -a Chromium desktop='^2'
bspc rule -a telegram-desktop desktop='^9'
bspc rule -a TelegramDesktop desktop='^9'
bspc rule -a mplayer2 state=floating
bspc rule -a oblogout state=fullscreen
bspc rule -a Oblogout state=fullscreen
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a mpv:security-cam-preview state=floating focus=off sticky=on
bspc rule -a mpv:security-cam-preview1 state=floating focus=off sticky=on
bspc rule -a mpv:security-cam-preview2 state=floating focus=off sticky=on
bspc rule -a mpv:security-cam-preview3 state=floating focus=off sticky=on
bspc rule -a stalonetray manage=off

# automatic_tab.py &
# two_tiled.py &
