#! /bin/sh

localectl --no-convert set-x11-keymap us,ara pc104 ,qwerty 'grp:alt_shift_toggle,caps:swapescape' &
setxkbmap -option "caps:escape" -option "altwin:menu_win" -option "terminate:ctrl_alt_bksp" &
perWindowLayoutD &
sxhkd &
xsetroot -cursor_name left_ptr &
picom &
optimus-manager-qt &
redshift &
goldendict &
nm-applet &
udiskie -t &
dunst -geometry "$((250*GDK_SCALE))x4-$((15*GDK_SCALE))+$((26*GDK_SCALE))" -padding $((8*GDK_SCALE)) -horizontal_padding $((10*GDK_SCALE)) -frame_width $((2*GDK_SCALE)) -font "Dejavu Sans Mono $((10*GDK_SCALE))" -corner_radius $((25*GDK_SCALE)) -min_icon_size $((32*GDK_SCALE)) -max_icon_size $((32*GDK_SCALE)) &
# /usr/lib/xfce4/notifyd/xfce4-notifyd &
blueman-applet &
emacs --daemon &
pasystray &
syncthing-gtk -m &
parcellite &
safeeyes &
mpd &
kdeconnect-indicator &
~/.config/bspwm/scripts/set_wallpaper.py &
notify-send.py "brightness notification" --replaces-process brightness_ctl -t 1 &
notify-send.py "volume notification" --replaces-process volume_ctl -t 1 &
if [ $HOSTNAME = "yusufs-lenovo" ]; then
    motion -b -c ~/.config/motion/motion.conf &
fi
~/.config/bspwm/bar/start_lemonbar.py &
xfce4-panel -d & # the best sys-tray of them all
# stalonetray -bg '#000000' --grow-gravity W -i 40 --sticky --geometry 10x1+1520+0 --dockapp-mode simple --window-type dock -d none --window-strut none --window-layer bottom --kludges force_icons_size &

# polybar mybar &
# fake configs folder to use a different gtk-3.0.ini file with a different font
# env XDG_CONFIG_HOME=$HOME/.config_alt xfce4-panel -d &

bspc monitor ^1 -d I II III IV V VI VII VIII IX X
bspc monitor ^2 -d 1 2 3 4 5 6 7 8 9 10

bspc config remove_unplugged_monitors true
bspc config removal_adjustment false

bspc config border_width        $((GDK_SCALE*3))
bspc config window_gap          $((GDK_SCALE*6))

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config automatic_scheme spiral

# colors
bspc config normal_border_color   "#44475a"
bspc config active_border_color   "#bd93f9"
bspc config focused_border_color  "#ff79c6"
bspc config presel_feedback_color "#6272a4"

for desk in {I,X,IX,VIII};do
bspc desktop $desk --layout monocle
done
#open Funny Java Things
# bspc config focus_follows_pointer false
wmname LG3D &

bspc config focus_follows_pointer true
bspc config external_rules_command "$(which external_rules)"
# bspc config pointer_follows_focus true

bspc config -m ^1 top_padding $((GDK_SCALE * 20))

bspc rule -a zathura state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a emacs state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a qutebrowser desktop='^1'
bspc rule -a Chromium desktop='^2'
bspc rule -a telegram-desktop desktop='^9' border=off
bspc rule -a TelegramDesktop desktop='^9'
bspc rule -a mplayer2 state=floating
bspc rule -a oblogout state=fullscreen
bspc rule -a Oblogout state=fullscreen
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a mpv:security-cam-preview state=floating focus=off sticky=on border=off
bspc rule -a mpv:security-cam-preview1 state=floating focus=off sticky=on border=off
bspc rule -a mpv:security-cam-preview2 state=floating focus=off sticky=on border=off
bspc rule -a mpv:security-cam-preview3 state=floating focus=off sticky=on border=off
bspc rule -a mpv:qutebrowser-youtube state=floating sticky=on focus=off
bspc rule -a stalonetray manage=off
bspc rule -a dropdown_terminal state=floating

~/.config/bspwm/scripts/swallow.py &
~/.config/bspwm/scripts/automatic_tab.py &
~/.config/bspwm/scripts/leave_empty_desk.py &
