#! /bin/sh

localectl --no-convert set-x11-keymap us,ara pc104 ,qwerty 'grp:alt_shift_toggle,caps:swapescape' &
setxkbmap -option caps:escape &
sxhkd &
xsetroot -cursor_name left_ptr &
compton -f --backend glx --glx-no-stencil -r 30 &
redshift &
goldendict &
nm-applet &
udiskie -t &
systemctl --user start xfce4-notifyd &
blueman-applet &
emacs --daemon &
pasystray &
syncthing-gtk -m &
parcellite &
safeeyes &
mpd &
kdeconnect-indicator &
~/.config/i3/dynamic_wallpaper.py &
notify-send.py "brightness notification" --replaces-process brightness_ctl -t 1 &
notify-send.py "volume notification" --replaces-process volume_ctl -t 1 &
motion -b -c ~/.config/motion/motion.conf &

# polybar mybar &
# fake configs folder to use a different gtk-3.0.ini file with a different font
env XDG_CONFIG_HOME=$HOME/.config_alt xfce4-panel -d &

bspc monitor ^1 -d I II III IV V VI VII VIII IX X
bspc monitor ^2 -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width        $((GDK_SCALE*2))
bspc config window_gap          $((GDK_SCALE*6))

bspc config split_ratio          0.7
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc desktop 'I' --layout monocle
#open Funny Java Things
# bspc config focus_follows_pointer false
wmname LG3D &

bspc config focus_follows_pointer true
bspc config external_rules_command "$(which external_rules)"
# bspc config pointer_follows_focus true

bspc config -m ^1 top_padding $((GDK_SCALE * 20))

# bspc rule -a xfce4-panel manage=off
# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a zathura state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a emacs state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a qutebrowser desktop='^1'
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a oblogout state=fullscreen
bspc rule -a Oblogout state=fullscreen
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a mpv:security-cam-preview state=floating focus=off sticky=on
bspc rule -a mpv:security-cam-preview1 state=floating focus=off sticky=on
bspc rule -a mpv:security-cam-preview2 state=floating focus=off sticky=on
bspc rule -a mpv:security-cam-preview3 state=floating focus=off sticky=on

automatic_tab.py &
# two_tiled.py &
