#! /usr/bin/env python3

import sys
import subprocess
from functools import partial

wid = sys.argv[1]
win_class = sys.argv[2]
instance = sys.argv[3]

cmd_run = partial(subprocess.Popen, text=True, shell=True)
cmd_output = partial(subprocess.check_output, text=True, shell=True)

try:
    floating = cmd_output(f'bspc query -N -n {wid}.floating').strip()
except subprocess.CalledProcessError:
    floating = ''

# print(wid, win_class, instance)
# print("'" + floating + "'")
if floating != '':
    print('layer=above')
# case $state in
#     floating)
#         bspc query -N -n .fullscreen.local >/dev/null && echo layer=above
# esac
