#!/usr/bin/env python

import os
import sys
import shlex
import tempfile
import subprocess as sp


def get_text():
    current_mode = os.getenv('QUTE_MODE')
    print(current_mode)
    text = 'No text found'
    if current_mode == 'hints':
        text = os.getenv('QUTE_SELECTED_TEXT')
    elif current_mode == 'command':
        text_path = os.getenv('QUTE_TEXT')
        if text_path and os.path.exists(text_path):
            with open(text_path, 'r') as f:
                text = f.read()
    print(text)
    return text


def create_tts_sound(text):
    text = shlex.quote(text)
    tmp = tempfile.NamedTemporaryFile()
    tmpfn = tmp.name
    print(tmpfn)
    P = sp.Popen(f'pico2wave --wave={tmpfn}.wav {text}',
                 shell=True, text=True)
    P.wait()
    if os.path.exists(tmpfn+'.wav'):
        return tmpfn+'.wav'
    return


def read_festival(text):
    tmp = tempfile.NamedTemporaryFile()
    tmpfn = tmp.name
    tmp.close()
    with open(tmpfn, 'w+') as f:
        f.write(text)
    print(tmpfn)
    sp.Popen(f'tsp festival --tts {shlex.quote(tmpfn)}', shell=True, text=True)
    sp.Popen(f'tsp rm {tmpfn}', shell=True)


def main():
    text = get_text()
    if len(sys.argv) == 1 or sys.argv[1] == 'pico':
        tmpfn = create_tts_sound(text)
        if tmpfn:
            sp.Popen(['tsp', 'play', tmpfn])
            sp.Popen(['tsp', 'rm', tmpfn])
    elif sys.argv[1] == 'festival':
        print('will use festival')
        read_festival(text)


if __name__ == '__main__':
    main()
